name: lint
on: [push, pull_request]
jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: ${{ hashFiles('**/go.sum') != '' }}
          cache-dependency-path: '**/go.sum'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          # Build with the runner's Go (1.25 from go.mod), not the prebuilt binary
          install-mode: goinstall
          version: 'latest'
          args: --timeout=3m
